### ISSUE TITLE
Cannot access secured services hosted on tiles.arcgis.com with the DotNet and PHP proxies

### ISSUE THREAD

**Issue by nhaney90** [Esri/resource-proxy#158] opened 2014-11-11 20:46 UTC
To reproduce this issue publish a tiled service to ArcGIS Online. Share this service only with your organization. In your PHP proxy put your AGOL username and password in a server URL tag along with the URL to the tiled service you just published. In the address bar of your browser try to access the tiled service by passing through the proxy similar to this:
http://csc-nhaney7d/PHP/proxy.php?https://tiles.arcgis.com/tiles/Wl7Y1m92PbjtJs5n/arcgis/rest/services/tileTest2/MapServer?f=json
You will receive a 499 error. I am able to access all other secured layers in AGOL using my PHP proxy,   I only have trouble accessing layers hosted on tiles.arcgis.com. You can also try this with your DotNet proxy. Sometimes I am able to access some layers hosted on tiles.arcgis.com with the DotNet proxy. I am also logging a bug for this issue in SalesForce.

**Comment by bsvensson** [comment] 2015-01-27 02:07
Closing this issue since the problem seemed to be specific to one service and not reproducible.

**Closed by bsvensson** 2015-01-27 02:07 UTC
Labels: *PHP*, invalid, wontfix

**Comment by roemhildtg** [comment] 2016-02-25 23:53
I'm experiencing this issue with sample servers, which shouldn't require authentication I had thought. For example, the following gives this error in the log file. 

`/proxy/proxy.php?http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/Petroleum/KSPetro/MapServer/1/`

And my config file has this line in it:

`<serverUrl url="http://sampleserver3.arcgisonline.com" matchAll="true"/>`

**Comment by intotecho** [comment] 2016-08-03 05:34
I get the same issue. I want to use the proxy for SSL, but don't require authentication.
So I have neither username/password nor oauth2 tokens in my config for this server.
Although it is actually neither .NET nor a secured service - so this is another issue.

**Comment by bsvensson** [comment] 2016-08-03 06:57
Hi @intotecho , if it's another issue, it's probably best to create a new separate github issue for it. When you do that, if possible, also try to add info on how to reproduce the issue.  Thanks :)

**Comment by intotecho** [comment] 2016-08-03 07:43
Hi @bsvensson, 
Good idea! I have created a new issue https://github.com/Esri/resource-proxy/issues/380
