### ISSUE TITLE
Java proxy page does not request a new OAuth2 token after a previous token has expired.

### ISSUE THREAD

**Issue by jesvinvalencia** [Esri/resource-proxy#138] opened 2014-08-08 22:46 UTC
Steps to reproduce:

1.  Install and configure the Java proxy page to proxy to an ArcGIS Online subscription-based service, such as traffic.arcgis.com or route.arcgis.com.

2.  Register a web application that uses the ArcGIS Online subscription-based service and embed the clientId and clientSecret in the proxy configuration file.  Test your application to ensure that it can access the services.

3.  Wait for the token expiration to elapse (default is 2 hours), then reopen the web application and use a tool that sends a request to the subscription-based service.  Notice that the Sign In dialog displays.  Using Fiddler or other network traffic inspection tool shows that the server returns an HTTP response code of 200, but the error "498: invalid token" is actually found in the response body.  The current Java proxy does not appear to correctly handle the case when a token has expired.

**Comment by cheetah90** [comment] 2015-08-11 20:46
This is the duplicate of #146. and has been fixed on JSP version thus the "Java" tag can be removed. @bsvensson

**Comment by bsvensson** [comment] 2015-08-18 22:20
Closing since it was fixed as part of #146

**Closed by bsvensson** 2015-08-18 22:20 UTC
Labels: *Java*
