### ISSUE TITLE
Feature request: support node.js (via Connect middleware)

### ISSUE THREAD

**Issue by RoyTinker** [Esri/resource-proxy#423] opened 2017-05-08 23:54 UTC
It would be great if a similar resource proxy existed for node.

**Comment by jgravois** [comment] 2017-05-09 03:36
we're discussing this in #63

**Comment by bsvensson** [comment] 2017-05-09 04:15
Closing as duplicate of #63

**Closed by bsvensson** 2017-05-09 04:15 UTC

**Comment by RoyTinker** [comment] 2017-05-09 22:10
Thanks @bsvensson @jgravois
